//
// Created by Xan Delayat on 27/05/2026.
//

#ifndef SUDOKUSOLVER_SUDOKU_TYPES_INTERNAL_H
#define SUDOKUSOLVER_SUDOKU_TYPES_INTERNAL_H

#include "sudoku_types.h"



#endif //SUDOKUSOLVER_SUDOKU_TYPES_INTERNAL_H