@startuml

struct SudokuTiles {
    char value
    char possible[9]
}

' stereotype **Subset

struct Affectation {
    SudokuTiles *tile
    char supposed
    char value
}

struct Grid {
    + initGrid()
    + dispFinal()
    + dispPossible()
    + setTileValue()
    + isGridValid()
    + backPlay()
}

Grid *-- "81  " SudokuTiles : grid
Grid *-- "*" Affectation : history

Affectation -[dotted]-> SudokuTiles

struct SubsetGrid {
    line : Subset
    col : Subset
    sub_square : Subset
}

struct SubsetSolver {
    + getLineSubset(n)
    + getColSubset(n)
    + getSubsqSubset(n)
    + buildAllSubsets()
    + cleanSubset(s)
    + solveHiddenSinglesInSubset(s)
    + cleanGrid()
    + solveHiddenSingles()
    + cleanNakedPairs()
    + cleanHiddenPairs()
    + cleanNakedTriples()
    + cleanHiddenTriples()
    + fixSubsets(s)
    + dispSubset(s)
    + freeAllSubsets()
    + cleanBoxLineReduction()
    + cleanPointingPairs()
    + cleanYWing()
    + cleanXWing()
    + cleanSwordfish()
    + cleanJellyfish()
    + cleanUniqueRectangle()
}

SubsetSolver -[dotted]-> SubsetGrid

SubsetGrid -[dotted]->  SudokuTiles

struct difficulty_t {
    unsigned short level
}

struct Verbose {
    char active;
    long nb_deductions;
    long nb_guesses;
    long nb_backplays;
}

struct Cli {
    static void printHelp(const char *cmd)
    char cli()
    static void generateLevelHelp()
    char verbose()
    static void traceVerbose(int row, int col, char val, char supposed)
    char benchmark()
    char interactive()
}

Cli -[dotted]-> Verbose
Cli -[dotted]-> Grid

struct Generate {
    char generateGrid(difficulty_t level, unsigned int seed)
}

Generate -[dotted]-> difficulty_t
Cli -[dotted]-> Generate

@enduml
