@startuml

struct SudokuTiles {
    char value
    char possible[9]
}

stereotype **Subset

struct Affectation {
    SudokuTiles *tile
    char supposed
    char value
}

struct difficulty_t {
    enum Difficulty
    TRIVIAL
    BASIC
    INTERMEDIATE
    HARD
    EXPERT
}

@enduml
